### ISSUE TITLE
Exapnding code for a larger number of characters

### ISSUE THREAD

**Issue by abuadan** [tharidu/breakingcaptcha#1]
Hi,

I'm wondering is it possible to scale this code to handle any length of captcha characters i.e. captchas of length 6, 7...11 etc.

**Comment by akash13singh** [comment]
Hi, 

It is not possible to handle captchas of any length with the current architecture. The current CNN has fixed number of output neurons i.e. 180 (5 * 36) and as such only works captchas with 5 characters. Though we can possibly modify it to detect captchas of any length up to 5. 

Right now for each of the 5 positions, we have 36 possible values, digits 0-9 alphabets (a-z). We can add one more neuron for each position which outputs a 0 or 1 depending on the absence or presence of a character for the position. So we will have 5*37 neurons in the output layer. Let's call these new neurons as position neurons. It may not be straightforward to train these position neurons as we do not do any pre-segmentation of images. But we can impose the order through training labels. For example, if we have only one character captcha, we will need to decide that only the first position neuron outputs a 1 and the rest output a 0. If we have a captcha with 3 characters the first three position neurons output 3 and the last two output 0. I think this approach will work and can be generalized to detect captchas with a maximum length _k_.

To detect captchas with any number of characters without any constraint, a sliding window approach where one moves a fixed size window over the image could be tried. So we can have output neuron which is trained only to output the number of characters in the captcha and then we loop over the image to output each character. Another approach could be to use RNNs. 

I am only speculating, it would be best to look into papers on multiple object detection.
