### ISSUE TITLE
Giving true value on wrong prediction

### ISSUE THREAD

**Issue by nabeel3133** [tharidu/breakingcaptcha#3]
So, I trained the model on my own dataset and tested it. It is giving 15% accuracy even though all the predictions are wrong as you can see in the image provided.
![Capture](https://user-images.githubusercontent.com/31992723/54679673-b2fa4800-4b29-11e9-8bd2-0cafaafbc834.PNG)

When I analyzed the true predictions, it is stating true even for words in which it outputs at least one character true in the correct position.
![Capture1](https://user-images.githubusercontent.com/31992723/54679681-b8f02900-4b29-11e9-9c69-b3edda1fb027.PNG)

Why is it giving true value for such predictions? Shouldn't the word be completely the same in order for it to be referred to as a true prediction?
![Capture2](https://user-images.githubusercontent.com/31992723/54679860-2ef49000-4b2a-11e9-90bd-65ecb028156e.PNG)

**Comment by akash13singh** [comment]
HI Nabeel,

The accuracy metric currently operates at character level. You can modify it to work at word level. As for the low accuracy it needs more data!

**Comment by nabeel3133** [comment]
Thank you for the clarification. 
Can you help me out in editing the accuracy metric so that it operates at word level? @akash13singh
